#!/bin/sh

version="$1"
bootdir=/boot
efidir=$bootdir/efi/EFI/Linux

# passing the kernel version is required
if [ -z "${version}" ]; then
  exit 0
fi

# absolute file name of kernel image may be passed as a second argument;
# remove the initrd from the same directory
if [ -n "$2" ]; then
  bootdir=$(dirname "$2")
  if [ ! -d "$bootdir" ]; then
    exit 1
  fi 
fi

# avoid running multiple times
if [ -n "$DEB_MAINT_PARAMS" ]; then
  if [ ! "${DEB_MAINT_PARAMS}" = "remove" ]; then
    exit 0
  fi
fi

# delete initramfs
rm -f "$bootdir/initrd.img-${version}"

[ -x /usr/bin/efibootmgr ] || exit 0

# unregister UEFI executable as boot entry
efibootmgr -B -L "Linux-${version}"
efibootmgr -B -L "Linux-${version}-rescue"

# delete UEFI executable
rm -f "$efidir/linux-${version}.efi"
rm -f "$efidir/linux-${version}-rescue.efi"


